### ISSUE TITLE
Create Q1 2020 Drone Pipeline Newsletter

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#24]
**Task to do**
Write newsletter for Q1 of 2020

**Reason**
Publishes progress made

**Result**
Have a Q1 Newsletter

**Comment by Chris-Schnaufer** [comment]
Pre-posting: https://docs.google.com/document/d/1UJLCNZvRr6eL5gNvjcAJztDJxmNbB7Z3rhiEBozCCbA/edit?usp=sharing

**Comment by Chris-Schnaufer** [comment]
Waiting for David to Review

**Comment by dlebauer** [comment]
This looks good - if you want to wait for the SPIE pre-print doi we could add that. Otherwise, go ahead and send it out!

**Comment by Chris-Schnaufer** [comment]
It's already up, so I'll just add the SPIE pre-print doi for next quarter if you're OK with that. Otherwise I can just add it.

**Comment by dlebauer** [comment]
Next quarter works as well

**Comment by Chris-Schnaufer** [comment]
Added new ticket for writing the Q2 2020 newsletter and wrote that it should include the SPIE pre-print doi: https://app.zenhub.com/workspaces/ua-ag-data-science-5a57a3198339f11ba1c85775/issues/agpipeline/drone-pipeline-environment/57
