### ISSUE TITLE
A missing timestamp causes problems with transformers

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#25]
**The current behavior or issue**
If a timestamp isn't specified in experimental dats it can cause transformers to crash

**The steps taken to reproduce the behavior or issue, or specify a location where the steps were recorded**
To reproduce leave out a timestamp in experiment data and run a susceptible transformer (plotclip for example)

**Expected behavior**
A missing timestamp should be handled gracefully

**Screenshots**
N/A

**Add other supporting information that may be useful**
N/A

**Completion criteria**
This is done when:
- [ ] a missing timestamp defaults to current date and transformers don't crash

Refer to code: https://github.com/AgPipeline/drone-pipeline-environment/blob/9f07b384146f8d5e946d35ce53c823b6e68469bf/base-transformer-class/transformer_class.py#L247

**Comment by jvanderleeuw** [comment]
The following is for issue #30: https://github.com/jvanderleeuw/Greenness_Transformer.git

**Comment by Chris-Schnaufer** [comment]
https://github.com/AgPipeline/drone-pipeline-environment/pull/54
