### ISSUE TITLE
OpenDroneMap ortho mosaics have significant geographic offset issues

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#29]
**The current behavior or issue**
The calculated ground positions of the ortho mosaic are quite a bit off from any reasonable answer. This needs to be accounted for so that good results can be produced

**The steps taken to reproduce the behavior or issue, or specify a location where the steps were recorded**
Run open drone map over a set of images and compare the resulting ortho mosaic with an accurate shapefile

**Expected behavior**
Running OpenDroneMap produces a reasonably accurate geographically referenced ortho mosaic image

**Screenshots**
N/A

**Add other supporting information that may be useful**
Open Drone Map version 0.9.1

**Completion criteria**
Determine if using ground control points produces accurate results

**Comment by Chris-Schnaufer** [comment]
Added support for gcp files

**Comment by Chris-Schnaufer** [comment]
Ground control point (GCP) files will definitely help resolve geographic alignment issues. The lack of GCP files should be used to indicate possible lack of data quality

**Comment by dlebauer** [comment]
How about GCPs should be required for the orthomosaicing and point cloud generation step
