### ISSUE TITLE
Add Greeness Transformer using RGB code template

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#30]
Take extractor algorithms from [google doc](https://docs.google.com/document/d/1cAm5w1Bs6dB1SHgf-HVmwwbebLhbZMUvTkXLtas_-xI/edit?usp=sharing)

**Comment by Chris-Schnaufer** [comment]
Please implement: Vegetative Index, Excess greenness index, and % Green. Others are welcome as well

**Comment by jvanderleeuw** [comment]
The following is a repository for this issue: https://github.com/jvanderleeuw/Greenness_Transformer.git

**Comment by Chris-Schnaufer** [comment]
https://github.com/jvanderleeuw/Greenness_Transformer/pull/4
