### ISSUE TITLE
Review Julians Work

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#36]
**Task to do**
Review Julian's SciFS work

**Reason**
Understand what Julian's work does

**Result**
Understanding of SciFS and what's next

**Comment by dlebauer** [comment]
please write out your assessment and next steps required if we adopt this approach

**Comment by dlebauer** [comment]
Notes from discussion https://hackmd.io/KJ2bgG9_RRCY3jr8jCRlsw?view

**Comment by Chris-Schnaufer** [comment]
Immediate follow-on work ticket: https://app.zenhub.com/workspaces/ua-ag-data-science-5a57a3198339f11ba1c85775/issues/agpipeline/drone-pipeline-environment/52

Additional tickets were written to bring this in line with existing code
