### ISSUE TITLE
Process Genome2Fields data

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#51]
Process Genome2Fields data on CyVerse /iplant/home/shared/commons_repo/curated/tamu_corn_2017_CS17_G2F_20190305

**Comment by Chris-Schnaufer** [comment]
Waiting on Ground Control Point (GCP) files mapping GCP to image file pixel locations

**Comment by dlebauer** [comment]
gcps are here: https://datacommons.cyverse.org/browse/iplant/home/shared/commons_repo/curated/tamu_corn_2017_CS17_G2F_20190305/CS17_G2F_GCPcoord.csv

They just aren't associated w/ specific files.
