### ISSUE TITLE
Write Q2 2020 Drone Pipeline Newsletter

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#57]
Be sure to include SPIE pre-print doi

**Comment by dlebauer** [comment]
Is that the [Q3_dpp_news.pages](https://drive.google.com/file/d/1twLqoGtvwEVLPVWUy8fRmD9L3ZTzfQHp/view?usp=sharing)? I don't have the pages app; could you put this in a google doc?

**Comment by Chris-Schnaufer** [comment]
Yes I can: https://docs.google.com/document/d/1WdJr3jgWHsnzeJiqX3PGZw1MF0K-sfNDVPNkJgXVod0/edit?usp=sharing

**Comment by Chris-Schnaufer** [comment]
@dlebauer What is the SPIE pre-print doi?

**Comment by Chris-Schnaufer** [comment]
Published: https://osf.io/xdkcy/wiki/News%20letters/
