### ISSUE TITLE
How To documentation needs additions related to testing.py

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#58]
**The current behavior or issue**
The current HOWTO isn't clear on what the testing.py output is and doesn't include steps on running it from within a docker container.

**The steps taken to reproduce the behavior or issue, or specify a location where the steps were recorded**
N/A

**Expected behavior**
The documentation should include this information

**Screenshots**
N/A

**Add other supporting information that may be useful**
N/A

**Completion criteria**
This is done when:
- [x] documentation updated to include expected outputs from running testing.py
- [x] documentation updated to include steps for running testing.py from within a docker image

Repo to update: https://github.com/AgPipeline/template-rgb-plot

**Comment by jvanderleeuw** [comment]
PR: https://github.com/AgPipeline/template-rgb-plot/pull/6

Issue resolved through documentation

**Comment by Chris-Schnaufer** [comment]
@jvanderleeuw Please don't close tickets before a sprint ends

**Comment by jvanderleeuw** [comment]
Thanks for letting me know. Is it during/after the sprint reviews that issues are closed?

**Comment by Chris-Schnaufer** [comment]
It is during sprint retrospective/review that we close them
