### ISSUE TITLE
The README in Organization repo isn't clear about copying the pylint.rc file

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#61]
**The current behavior or issue**
The current [Python](https://github.com/AgPipeline/Organization-info#python) documentation recommends copying the `pylint.rc` file into repositories. It should be clear that that step is only for non-AgPipeline repos

**The steps taken to reproduce the behavior or issue, or specify a location where the steps were recorded**
Read the documentation

**Expected behavior**
The documentation should be clear that AgPipeline repos don't add the `pylint.rc` to their code bases

**Screenshots**
![Screen Shot 2020-05-21 at 12.53.02 PM.png](https://images.zenhubusercontent.com/5c14118eee1e975f1842e1c2/1258986b-ae83-48fe-a151-34e999522537)

**Add other supporting information that may be useful**
N/A

**Completion criteria**
This is done when the documentation is updated

**Comment by Chris-Schnaufer** [comment]
https://github.com/AgPipeline/Organization-info/pull/5

**Comment by dlebauer** [comment]
Why not follow recommendations to have the file in the repo?

**Comment by Chris-Schnaufer** [comment]
When/if it changes then the repos wouldn't be automatically up to date in their pylint check. If they rely on Organization copy, then they're always up to date
