### ISSUE TITLE
Remove pyclowder and terrautils dependencies from transformer-opendronemap

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#63]
**Task to do**
Remove any dependencies on pyclowder and terrautils libraries from the code. This should be done by creating equivalent files/functions in agpypeline library; the use of the original names is not required.

**Reason**
The pyclowder and terrautils libraries are specific to Clowder and TERRA REF which are not an integral part of AgPipeline (although AgPipeline code can be made to work in those environments)

**Result**
The agpypeline library will replace pyclowder and terrautils.

**Completion Criteria**
[ ] Python3.7 or later are the only supported versions (earlier versions may use the library, but it's not "officially" supported)
[ ] agpypeline library is installed 
[ ] pyclowder and terrautils are not installed
[ ] Test run is successful

**Comment by jvanderleeuw** [comment]
https://github.com/AgPipeline/transformer-opendronemap/pull/14
