### ISSUE TITLE
Derive transformer-opendronemap source from agpypeline library

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#64]
**Task to do**
Derive the transformer-opendronemap `entrypoint.py` and `environment.py` instances from the common code in the agpypeline library. Geometry-based functions in transformer-opendronemap should be placed in agpypeline's geoimage.py file.

**Reason**
By limiting the uniqueness of the transformer-opendronemap solution, it's easier to maintain and more in line with programming best practices.

**Result**
The transformer-opendronemap repo makes use of the agpypeline library as much as possible

**Comment by jvanderleeuw** [comment]
https://github.com/AgPipeline/transformer-opendronemap/pull/14
