### ISSUE TITLE
Remove pyclowder and terrautils dependencies from agpypeline library

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#65]
**Task to do**
Replace pyclowder and terrautils library dependencies with agpypeline-base code. Code needs to be Python 3.7, or better, compliant; older versions may support the library, but that's not required

**Reason**
The pyclowder and terrautils libraries are for specific projects and having a dependency upon them brings in  unused code and features. The AgPipeline solutions are compatible with those libraries, but shouldn't be dependent upon them.

**Result**
The requirements on pyclowder and terrautils libraries are replaced by the agpypeline library

**Comment by jvanderleeuw** [comment]
https://github.com/AgPipeline/agpypeline/pull/5

**Comment by KristinaRiemer** [comment]
@jvanderleeuw why was this pull request closed? Should it have been merged?
