### ISSUE TITLE
Convert non-geojson plot geometry files to geojson as part of scif workflow

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/drone-pipeline-environment#70]
**Task to do**
Add conversions from shapefile and BETYdb to geojson

**Reason**
The transformers should work with OGC compliant formats only

**Result**
Plotclip only handles geojson format. Conversion from other formats happens earlier in workflow

See https://app.zenhub.com/workspaces/ua-ag-data-science-5a57a3198339f11ba1c85775/issues/agpipeline/drone-pipeline-environment/69

**Comment by dlebauer** [comment]
is this in one of the open PRs?

**Comment by Chris-Schnaufer** [comment]
Darn, I missed this. Yes, it's PR https://github.com/AgPipeline/drone-makeflow/pull/3
